spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: aisino2017
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    dispatch-options-request: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.htxx.entity
server:
  port: 8090
